import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { CookiesProvider } from "next-client-cookies/server";

import "./globals.css";
import { Header } from "./header";
import { Toaster } from "@/components/ui/toaster";
import { TanstackProvider } from "@/components/providers/TanstackProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={
          poppins.className + " min-h-screen bg-primary-light scroll-m-14"
        }
        id="body"
      >
        <CookiesProvider>
          <TanstackProvider>
            <Toaster />
            <Header /> {children}
          </TanstackProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
